# Generated by Django 3.1.7 on 2021-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uygulama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=120)),
                ('birt_date', models.DateTimeField()),
                ('id_nummer', models.DateTimeField()),
                ('gender', models.TextField()),
                ('school', models.TextField()),
            ],
        ),
    ]
