# Generated by Django 3.1.7 on 2021-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uygulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uygulama',
            name='birt_date',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='gender',
            field=models.CharField(max_length=120, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='id_nummer',
            field=models.CharField(max_length=11, verbose_name='TC Numarası'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='name_surname',
            field=models.CharField(max_length=120, verbose_name='İsim-Soyisim'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='school',
            field=models.TextField(verbose_name='Okul'),
        ),
    ]
